<footer class="footer-bg footer-p" >           
            <div class="footer-top pt-120 pb-190" style="background:url(img/bg/footer-bg.png) no-repeat; background-size: cover;">
                <div class="container">
                    <div class="row align-items-center">
                        
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                            <div class="footer-widget text-center mb-30">
                                <div class="flog mt-50 mb-30">
                                    <a href="#"><img src="img/logo/logo.png" alt="logo"></a>
                                </div>
                                <div class="footer-text mb-20">
                                    <p></p>
                                </div>
                                <div class="footer-social  mt-30">
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                    <a href="#"><i class="fab fa-google-plus-g"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                            <div class="footer-widget mb-30 text-center">
                                 <div class="f-time-icon">
                                    <img src="img/bg/time-bg.png" alt="logo">
                                </div>
                                <div class="f-widget-title mt-100">
                                    <span>french bistro</span>
                                    <h5>Часы работы</h5>
                                </div>
                                <div class="footer-link">
                                    <div class="f-time">
                                        <ul>
                                            <li><div class="day">Пн - Чт</div>
                                                <div class="time">9.00 - 22.00</div> </li>
                                            <li><div class="day">Пт - Сб</div> <div class="time">9.00 - 22.00</div> </li>
                                        </ul>
                                    </div>
                                   
                                    
                                </div>
                            </div>
                        </div>  
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                            <div class="footer-widget mb-30 text-center">
                                   <div class="f-contact-icon">
                                    <img src="img/bg/f-contact-icon.png" alt="logo">
                                </div>
                                <div class="f-widget-title mt-100">
                                    <span>Контакты</span>
                                    <h5></h5>
                                </div>
                                <div class="footer-link">
                                    <div class="f-contact">
                                    <p>Россия, Биробиджан, Пионерская, 64/а</p>
                                    <a href="" class="btn ss-btn mt-20">Подробнее</a>
                                    </div>
                                   
                                    
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
    
        </footer>